### ISSUE TITLE
Animation - Processing Sketch Requirements

### ISSUE THREAD

**Issue by arudaev** [THD-AI-2023/AIN-B-1-Programming-1-WS23#7]
Please ensure the following for the animation task:

- Drawing area dimensions: 640x480px.
- Include non-animated elements in the background (> 5 elements. Don't use too many).
- Create an animated "thing" (> 5 elements) that moves from left to right (or top down).
- If the animated "thing" exits the drawing area, ensure it re-enters from the opposite side.

Additional Instructions:
- Adhere to the guidelines provided in `exercise_performance_00_general.pdf`.
- Properly comment your code following the directives in `02_Comments_Variables.pdf`.
- Capture 2 frames of your animation to show what is being animated.
- Naming:
  - Code: `task_2_animation.pde`
  - Images: `task_2_animation_1.tif` and `task_2_animation_2.tif`
- Submit both the images (.tif) and sketch (.pde) on iLearn.

**Comment by HlexNC** [comment]
# Task 2: Animation

The task 2 of the exercise performance (LN). Write a Processing sketch that has an animated element. Conditions:
- Follow the rules written down in `exercise_performance_00_general.pdf`.
- The size of the drawing area is 640x480px.
- Have some non-animated drawing in the background (> 5 elements. Don't use too many).
- Have an animated "thing" (> 5 elements) flying from left to right (or top down).
- When the "thing" leaves the drawing area, let it come back from the opposite side.
- Comment your sketch properly (the rules are given in slides `02_Comments_Variables.pdf`).
- Store 2 frames of your animation as images (that show what's animated).
- The sketch must be named `task_2_animation.pde` and the images `task_2_animation_1.tif` and `task_2_animation_2.tif`.
- Hand in the images (.tif) and sketch (.pde) in iLearn!
